# Generated by Django 3.1.3 on 2020-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40, null=True)),
                ('year', models.DateField()),
                ('manufactuer', models.TextField(max_length=40, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Manufactuers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40, null=True)),
                ('country', models.TextField(max_length=40, null=True)),
                ('logo', models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to='logo')),
            ],
        ),
    ]
