# Generated by Django 3.1.3 on 2020-11-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
